[WIP] Refactor and support encoding to timestamp and decoding to date
alickbass/CodableFirebase pull request #58
Opened 2018-11-03 09:09 UTC by caoer

I'd like to keep the model clean, without any dependency from firestore, which limits us to use Date, and not Timestamp. This PR adds an ability of it. 

I also refactor and clean the code a bit.

I haven't use and test other types. gonna work on them later...

2018-11-03 09:16 UTC, caoer commented
```
FirestoreEncoder(userInfo: [
            CodingUserInfoKey.dateEncodingStrategy:
                DateEncodingStrategy.deferredToTimestamp({ Timestamp(date: $0) })
            ])
```

```
FirestoreDecoder(userInfo: [
            CodingUserInfoKey.dateDecodingStrategy:
                DateDecodingStrategy.deferredToTimestamp
            ])
```

2018-11-09 10:33 UTC, alickbass requested changes
Hi! Thanks a lot for working on this! TBH, this Pull request is massive, it is really hard to review it. Could you please split it to smaller pull requests with more concrete goals? And about cleaning up, the way the code is organized now is intentional, to reflect the structure of the JSONEncoder and JSONDecoder in apple/swift, so I would prefer to keep it as close to that as possible

2019-01-21 11:51 UTC, agordeev commented
It'd be great to see this merged so we could map Date to Timestamp

2019-02-18 23:32 UTC, jimijon commented
CAN WE GET THIS INTO MASTER?

2019-07-19 11:19 UTC, inquisitiveSoft commented
This looks awesome. Any chance we could get this merged?
It's not *that* long, considering most of it is pretty boilerplate-y

2019-10-27 17:32 UTC, bradleymackey commented
Bump

2025-08-31 21:09 UTC, closed without merging